### PR TITLE
refactor: method to validate entity type from raw string form of urn

### PR DESCRIPTION
**Pull request by jywadhwani**
## Checklist

- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by jywadhwani** [comment]
primarily to bring this change back https://github.com/linkedin/datahub/pull/1958

**Comment by keremsahin1** [comment]
How does this aling with https://github.com/linkedin/datahub-gma/pull/27 ?

**Comment by jplaisted** [comment]
Please do not change `Urn` ever! At this point let's keep it totally in sync with the definition we have internally. I added a `Urns` class we can add to instead.

**Comment by jplaisted** [comment]
Also, why do we need this? Is writing `validateUrn(new Urn(str, type))` that frequent?

**Comment by jywadhwani** [comment]
intended to call `validateUrn` in urn definitions of each entity. Looks like we are not going to be using a util function anymore to validate the same (as per https://github.com/linkedin/datahub/pull/1977/files) - in favor of code gen.

Will discard this PR.

**Pull request closed without merging**
