### PR TITLE
feat: add browse DAO integration tests for elasticsearch

### PR DESCRIPTION
**Pull request by jplaisted**
## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by jplaisted** [comment]
Depends on https://github.com/linkedin/datahub-gma/pull/72

**Review by camelliazhang — APPROVED** [review]
LGTM in general.
Can we add test case for "BrowseResultMetadata"? It also shows a list of groups and total number of entities inside those groups under the queried path. Separate PR works too.

**Comment by jplaisted** [comment]
> LGTM in general.
> Can we add test case for "BrowseResultMetadata"? It also shows a list of groups and total number of entities inside those groups under the queried path. Separate PR works too.

Good catch, I'll do it here.

**Comment by jplaisted** [comment]
Added test.

**Comment by camelliazhang** [comment]
> > LGTM in general.
> > Can we add test case for "BrowseResultMetadata"? It also shows a list of groups and total number of entities inside those groups under the queried path. Separate PR works too.
> 
> Good catch, I'll do it here.

Thanks!

**Pull request merged**
